security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
hdfs:
  #superuser for hdfs
  superuser: ${hdfs.user:hdfs}
  #path on hdfs where broker creates dirs for user apps
  userspace.chroot: ${broker.userspace.path:/org/%{organization}/brokers/userspace/%{instance}}
  #encoded hadoop configuration files for hdfs
  provided.zip: ${hadoop.provided.zip:{}}
  #keytab for hdfs superuser, which will create encrypted zones
  keytab: ${hdfs.keytab:{}}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/hdfs/metadata}
cf:
  #name of service in cloud foundry catalog
  servicename: ${cf.catalog.servicename:hdfs}
  #id of service in cloud foundry catalog
  serviceid: ${cf.catalog.serviceid:hdfs}
  #id of base plan in cloud foundry catalog
  baseId: ${BASE_GUID:}
metadata:
  #encoded image file viewed in marketplace
  imageUrl: ${IMAGE_URL:}
